name: env_gridworld
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=3.5.0
  - argon2-cffi=20.1.0
  - attrs=22.1.0
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - blas=1.0
  - bleach=4.1.0
  - ca-certificates=2023.08.22
  - certifi=2020.6.20
  - cffi=1.15.1
  - colorama=0.4.6
  - comm=0.1.4
  - console_shortcut=0.1.1
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - flit-core=3.6.0
  - freetype=2.12.1
  - giflib=5.2.1
  - idna=3.4
  - importlib-metadata=4.11.3
  - importlib_metadata=4.11.3
  - importlib_resources=5.2.0
  - intel-openmp=2021.4.0
  - ipykernel=6.15.2
  - ipython=7.31.1
  - ipython_genutils=0.2.0
  - ipywidgets=8.1.1
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - jsonschema=4.17.3
  - jupyter_client=7.4.9
  - jupyter_core=4.11.2
  - jupyter_server=1.23.4
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=3.0.9
  - lerc=3.0
  - libdeflate=1.17
  - libpng=1.6.39
  - libsodium=1.0.18
  - libtiff=4.5.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - nbclassic=0.5.2
  - nbclient=0.5.13
  - nbconvert=6.4.4
  - nbformat=5.7.0
  - nest-asyncio=1.5.6
  - ninja=1.10.2
  - ninja-base=1.10.2
  - notebook=6.5.2
  - notebook-shim=0.2.2
  - numpy=1.21.5
  - numpy-base=1.21.5
  - openssl=1.1.1w
  - packaging=22.0
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pickleshare=0.7.5
  - pillow=9.3.0
  - pip=22.3.1
  - pkgutil-resolve-name=1.3.10
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - pycparser=2.21
  - pygments=2.11.2
  - pyrsistent=0.18.0
  - python=3.7.16
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - pywin32=305
  - pywinpty=2.0.10
  - pyzmq=23.2.0
  - send2trash=1.8.0
  - setuptools=65.6.3
  - six=1.16.0
  - sniffio=1.2.0
  - soupsieve=2.3.2.post1
  - sqlite=3.41.2
  - terminado=0.17.1
  - testpath=0.6.0
  - tk=8.6.12
  - tornado=6.2
  - traitlets=5.7.1
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.38.4
  - widgetsnbextension=4.0.9
  - wincertstore=0.2
  - winpty=0.4.3
  - xz=5.4.2
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - blis==0.7.11
      - cached-property==1.5.2
      - catalogue==2.0.10
      - charset-normalizer==3.3.0
      - click==8.1.7
      - cloudpathlib==0.15.1
      - confection==0.1.3
      - cycler==0.11.0
      - cymem==2.0.8
      - distro==1.9.0
      - en-core-web-sm==3.7.1
      - filelock==3.12.2
      - fonttools==4.38.0
      - fsspec==2023.1.0
      - h11==0.14.0
      - httpcore==0.17.3
      - httpx==0.24.1
      - huggingface-hub==0.16.4
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - langcodes==3.3.0
      - matplotlib==3.5.3
      - murmurhash==1.0.10
      - openai==1.39.0
      - opencv-python==4.8.1.78
      - pandas==1.3.5
      - pathy==0.10.2
      - preshed==3.0.9
      - py-cpuinfo==9.0.0
      - pydantic==1.10.13
      - pyparsing==3.1.1
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - regex==2023.10.3
      - requests==2.31.0
      - safetensors==0.3.3
      - scikit-learn==1.0.2
      - scipy==1.7.3
      - seaborn==0.12.2
      - smart-open==6.4.0
      - spacy==3.7.6
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.4.8
      - thinc==8.2.5
      - threadpoolctl==3.1.0
      - tokenizers==0.13.3
      - torch==1.13.1
      - torchvision==0.14.1
      - tqdm==4.66.1
      - transformers==4.30.2
      - typer==0.9.0
      - typing-extensions==4.7.1
      - ultralytics==8.0.145
      - urllib3==2.0.6
      - vadersentiment==3.3.2
      - wasabi==1.1.2
      - weasel==0.3.2
